openapi: 3.0.0
info:
  title: SP Projet APIs
  version: 1.0.0
  description:  
components:
  schemas:
    User:
      type: object
      properties:
        id :
          type: integer
        lastname:
          type: string
        firstname:
          type: string
        confirmation:
          type: boolean
        confirmation_dej:
          type: boolean
        confirmation_balade:
          type: boolean
        confirmation_diner:
          type: boolean
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []