openapi: 3.0.0
info:
  title: SP Projet APIs
  version: 1.0.0
  description:  
components:
  schemas:
    User:
      type: object
      properties:
        lastname:
          type: string
        firstname:
          type: string
        mdp:
          type: string
        code:
          type: string
        confirmation:
          type: boolean
